### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by FischLu** [cid0rz/CTS-Cidorz-Train-System#1]
What's the difference between the idea from this repository and  Logistic Train Network?

**Comment by cid0rz** [comment]
Hi and thanks for the interest and for the compliment as LTN is a very nice mod. They are both scheduling systems for trains. LTN is implemented as a mod in Lua and this one is a series of asm programs that run on a modded entity, the fCPU's, that are small micro-controllers for factorio combinators basically. 
The main differences with LTN are:
* In this system all the stations have to be connected with red wire
* you can't have multiple depots on the same network (with LTN you can)
* the order of the stations in the list and the length of the station list may yield long booking times (so for big networks I have not tested if its comparable in efficiency).
* the setup and maintenance is more complex/error prone
* you can hack the system to work as you please :)

If you need further info or some part needs clarification please com back to me.

**Comment by cid0rz** [comment]
so @FischLu if everything is clear for you, may I close this issue?

**Comment by FischLu** [comment]
> 
> 
> so @FischLu if everything is clear for you, may I close this issue?

Yes, thank you very much. I am also a fan of fCPU, nice to know this repository.

**Comment by cid0rz** [comment]
you are welcome, I hope you enjoy and make also nice contributions to the fCPU and Factorio ecosystem :).
